In [1]:
import pandas as pd
import numpy as np

In [2]:
cd data

/Users/alexiscarlier/Desktop/S2/Applied_Econometrics/data

In [3]:
df_before_78 = pd.read_csv('before_78_1.csv')

/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

## Deleting data that was incorrectly entered by the surveyors

In [4]:
clean_before_78_1 = df_before_78[pd.notnull(df_before_78['parcel'])]

In [5]:
before_78_2 = pd.read_csv('before_78_2.csv')

/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [6]:
before_78_2.head()

,Unnamed: 0,home_id,parcel,amount,month,year,usage_type,unit,gco2e_coefficient,subdivision_id,subdivision,apartment_id,apartment,squarefeet,zip,builtin,beds,baths,stories,family
0,1,167394,13451-002-000,10150.0,12.0,2000.0,CO2e,g,1.0,2643.0,WILSONS S/D MILLER BLOCK,NaN,NaN,2486,32602,1975,4,2.0,2,multi family
1,2,167394,13451-002-000,9425.0,1.0,2001.0,CO2e,g,1.0,2643.0,WILSONS S/D MILLER BLOCK,NaN,NaN,2486,32602,1975,4,2.0,2,multi family
2,3,167394,13451-002-000,10150.0,2.0,2001.0,CO2e,g,1.0,2643.0,WILSONS S/D MILLER BLOCK,NaN,NaN,2486,32602,1975,4,2.0,2,multi family
3,4,167394,13451-002-000,7250.0,3.0,2001.0,CO2e,g,1.0,2643.0,WILSONS S/D MILLER BLOCK,NaN,NaN,2486,32602,1975,4,2.0,2,multi family
4,5,167394,13451-002-000,9425.0,4.0,2001.0,CO2e,g,1.0,2643.0,WILSONS S/D MILLER BLOCK,NaN,NaN,2486,32602,1975,4,2.0,2,multi family

In [7]:
clean_before_78_2 = before_78_2[pd.notnull(before_78_2['parcel'])]

In [8]:
len(set(list(clean_before_78_2['home_id'])))

61

In [9]:
len(set(list(clean_before_78_1['home_id'])))

119

In [10]:
clean_before_78 = pd.concat([clean_before_78_1, clean_before_78_2], ignore_index=True)

In [11]:
len(set(list(clean_before_78['home_id'])))

180

In [12]:
df_1974 = pd.read_csv('1974.csv')

In [13]:
len(set(list(df_1974['home_id']))) + 180

228

## This is the correct(ish) version of the before 1978 data

In [14]:
clean_before_78 = pd.concat([clean_before_78, df_1974], ignore_index=True)

In [15]:
len(set(list(clean_before_78['home_id'])))

228

## Now for the post 1978 data

In [16]:
post_78 = pd.read_csv('datafrom79.csv')

/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

### Deleting (more!) data that was incorrectly entered by the surveyors

In [17]:
clean_79 = post_78[pd.notnull(post_78['parcel'])]

In [18]:
df_1982 = pd.read_csv('1982.csv')

/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [19]:
df_1982 = df_1982[pd.notnull(df_1982['parcel'])]

In [20]:
len(set(list(df_1982['home_id'])))

49

In [21]:
clean_post_78 = pd.concat([clean_79, df_1982], ignore_index=True)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  """Entry point for launching an IPython kernel.

#### One of the houses is incorrectly entered in the database as being built in both 1977 and 1982...

In [22]:
def intersection(lst1, lst2): 
    return list(set(lst1) & set(lst2))

In [23]:
intersection(list(clean_post_78['home_id']), clean_before_78['home_id'])

['162311']

In [24]:
clean_post_78[clean_post_78['home_id'] == '162311']

,Unnamed: 0,amount,apartment,apartment_id,baths,beds,builtin,family,gco2e_coefficient,home_id,month,parcel,squarefeet,stories,subdivision,subdivision_id,unit,usage_type,year,zip
114595,14329.0,692850.0,NaN,NaN,2.0,3,1982,single family,1.0,162311,10.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,g,CO2e,1999.0,32607
114596,14330.0,729700.0,NaN,NaN,2.0,3,1982,single family,1.0,162311,11.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,g,CO2e,1999.0,32607
114597,14331.0,991025.0,NaN,NaN,2.0,3,1982,single family,1.0,162311,12.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,g,CO2e,1999.0,32607
114598,14332.0,1367400.0,NaN,NaN,2.0,3,1982,single family,1.0,162311,1.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,g,CO2e,2000.0,32607
114599,14333.0,1161600.0,NaN,NaN,2.0,3,1982,single family,1.0,162311,2.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,g,CO2e,2000.0,32607
114600,14334.0,853525.0,NaN,NaN,2.0,3,1982,single family,1.0,162311,3.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,g,CO2e,2000.0,32607
114601,14335.0,756800.0,NaN,NaN,2.0,3,1982,single family,1.0,162311,4.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,g,CO2e,2000.0,32607
114602,14336.0,812025.0,NaN,NaN,2.0,3,1982,single family,1.0,162311,5.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,g,CO2e,2000.0,32607
114603,14337.0,1411800.0,NaN,NaN,2.0,3,1982,single family,1.0,162311,6.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,g,CO2e,2000.0,32607
114604,14338.0,1520700.0,NaN,NaN,2.0,3,1982,single family,1.0,162311,7.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,g,CO2e,2000.0,32607
114605,14339.0,1235450.0,NaN,NaN,2.0,3,1982,single family,1.0,162311,8.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,g,CO2e,2000.0,32607
114606,14340.0,1132450.0,NaN,NaN,2.0,3,1982,single family,1.0,162311,9.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,g,CO2e,2000.0,32607
114607,14341.0,571625.0,NaN,NaN,2.0,3,1982,single family,1.0,162311,10.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,g,CO2e,2000.0,32607
114608,14342.0,700500.0,NaN,NaN,2.0,3,1982,single family,1.0,162311,11.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,g,CO2e,2000.0,32607
114609,14343.0,1061675.0,NaN,NaN,2.0,3,1982,single family,1.0,162311,12.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,g,CO2e,2000.0,32607
114610,14344.0,1609675.0,NaN,NaN,2.0,3,1982,single family,1.0,162311,1.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,g,CO2e,2001.0,32607
114611,14345.0,742975.0,NaN,NaN,2.0,3,1982,single family,1.0,162311,2.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,g,CO2e,2001.0,32607
114612,14346.0,511925.0,NaN,NaN,2.0,3,1982,single family,1.0,162311,3.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,g,CO2e,2001.0,32607
114613,14347.0,499225.0,NaN,NaN,2.0,3,1982,single family,1.0,162311,4.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,g,CO2e,2001.0,32607
114614,14348.0,749575.0,NaN,NaN,2.0,3,1982,single family,1.0,162311,5.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,g,CO2e,2001.0,32607
114615,14349.0,1091600.0,NaN,NaN,2.0,3,1982,single family,1.0,162311,6.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,g,CO2e,2001.0,32607
114616,14350.0,1584150.0,NaN,NaN,2.0,3,1982,single family,1.0,162311,7.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,g,CO2e,2001.0,32607
114617,14351.0,1212325.0,NaN,NaN,2.0,3,1982,single family,1.0,162311,8.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,g,CO2e,2001.0,32607
114618,14352.0,750225.0,NaN,NaN,2.0,3,1982,single family,1.0,162311,9.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,g,CO2e,2001.0,32607
114619,14353.0,530100.0,NaN,NaN,2.0,3,1982,single family,1.0,162311,10.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,g,CO2e,2001.0,32607
114620,14354.0,507875.0,NaN,NaN,2.0,3,1982,single family,1.0,162311,11.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,g,CO2e,2001.0,32607
114621,14355.0,471875.0,NaN,NaN,2.0,3,1982,single family,1.0,162311,12.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,g,CO2e,2001.0,32607
114622,14356.0,1010875.0,NaN,NaN,2.0,3,1982,single family,1.0,162311,1.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,g,CO2e,2002.0,32607
114623,14357.0,664375.0,NaN,NaN,2.0,3,1982,single family,1.0,162311,2.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,g,CO2e,2002.0,32607
114624,14358.0,462075.0,NaN,NaN,2.0,3,1982,single family,1.0,162311,3.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,g,CO2e,2002.0,32607
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115640,15374.0,4.0,NaN,NaN,2.0,3,1982,single family,725.0,162311,7.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,kGal,water,2016.0,32607
115641,15375.0,4.0,NaN,NaN,2.0,3,1982,single family,725.0,162311,8.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,kGal,water,2016.0,32607
115642,15376.0,4.0,NaN,NaN,2.0,3,1982,single family,725.0,162311,9.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,kGal,water,2016.0,32607
115643,15377.0,4.0,NaN,NaN,2.0,3,1982,single family,725.0,162311,10.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,kGal,water,2016.0,32607
115644,15378.0,3.0,NaN,NaN,2.0,3,1982,single family,725.0,162311,11.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,kGal,water,2016.0,32607
115645,15379.0,3.0,NaN,NaN,2.0,3,1982,single family,725.0,162311,12.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,kGal,water,2016.0,32607
115646,15380.0,3.0,NaN,NaN,2.0,3,1982,single family,725.0,162311,1.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,kGal,water,2017.0,32607
115647,15381.0,4.0,NaN,NaN,2.0,3,1982,single family,725.0,162311,2.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,kGal,water,2017.0,32607
115648,15382.0,2.0,NaN,NaN,2.0,3,1982,single family,725.0,162311,3.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,kGal,water,2017.0,32607
115649,15383.0,3.0,NaN,NaN,2.0,3,1982,single family,725.0,162311,4.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,kGal,water,2017.0,32607
115650,15384.0,3.0,NaN,NaN,2.0,3,1982,single family,725.0,162311,5.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,kGal,water,2017.0,32607
115651,15385.0,3.0,NaN,NaN,2.0,3,1982,single family,725.0,162311,6.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,kGal,water,2017.0,32607
115652,15386.0,3.0,NaN,NaN,2.0,3,1982,single family,725.0,162311,7.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,kGal,water,2017.0,32607
115653,15387.0,4.0,NaN,NaN,2.0,3,1982,single family,725.0,162311,8.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,kGal,water,2017.0,32607
115654,15388.0,4.0,NaN,NaN,2.0,3,1982,single family,725.0,162311,9.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,kGal,water,2017.0,32607
115655,15389.0,4.0,NaN,NaN,2.0,3,1982,single family,725.0,162311,10.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,kGal,water,2017.0,32607
115656,15390.0,3.0,NaN,NaN,2.0,3,1982,single family,725.0,162311,11.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,kGal,water,2017.0,32607
115657,15391.0,4.0,NaN,NaN,2.0,3,1982,single family,725.0,162311,12.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,kGal,water,2017.0,32607
115658,15392.0,4.0,NaN,NaN,2.0,3,1982,single family,725.0,162311,1.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,kGal,water,2018.0,32607
115659,15393.0,4.0,NaN,NaN,2.0,3,1982,single family,725.0,162311,2.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,kGal,water,2018.0,32607
115660,15394.0,4.0,NaN,NaN,2.0,3,1982,single family,725.0,162311,3.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,kGal,water,2018.0,32607
115661,15395.0,5.0,NaN,NaN,2.0,3,1982,single family,725.0,162311,4.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,kGal,water,2018.0,32607
115662,15396.0,4.0,NaN,NaN,2.0,3,1982,single family,725.0,162311,5.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,kGal,water,2018.0,32607
115663,15397.0,6.0,NaN,NaN,2.0,3,1982,single family,725.0,162311,6.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,kGal,water,2018.0,32607
115664,15398.0,6.0,NaN,NaN,2.0,3,1982,single family,725.0,162311,7.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,kGal,water,2018.0,32607
115665,15399.0,9.0,NaN,NaN,2.0,3,1982,single family,725.0,162311,8.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,kGal,water,2018.0,32607
115666,15400.0,4.0,NaN,NaN,2.0,3,1982,single family,725.0,162311,9.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,kGal,water,2018.0,32607
115667,15401.0,5.0,NaN,NaN,2.0,3,1982,single family,725.0,162311,10.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,kGal,water,2018.0,32607
115668,15402.0,2.0,NaN,NaN,2.0,3,1982,single family,725.0,162311,11.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,kGal,water,2018.0,32607
115669,15403.0,4.0,NaN,NaN,2.0,3,1982,single family,725.0,162311,12.0,06528-029-000,1836,1,ANGLEWOOD REPLAT,NaN,kGal,water,2018.0,32607

In [25]:
clean_before_78[clean_before_78['home_id'] == '162311']

,Unnamed: 0,home_id,parcel,amount,month,year,usage_type,unit,gco2e_coefficient,subdivision_id,subdivision,apartment_id,apartment,squarefeet,zip,builtin,beds,baths,stories,family
12397,13443,162311,06528-029-000,692850.0,10.0,1999.0,CO2e,g,1.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
12398,13444,162311,06528-029-000,729700.0,11.0,1999.0,CO2e,g,1.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
12399,13445,162311,06528-029-000,991025.0,12.0,1999.0,CO2e,g,1.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
12400,13446,162311,06528-029-000,1367400.0,1.0,2000.0,CO2e,g,1.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
12401,13447,162311,06528-029-000,1161600.0,2.0,2000.0,CO2e,g,1.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
12402,13448,162311,06528-029-000,853525.0,3.0,2000.0,CO2e,g,1.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
12403,13449,162311,06528-029-000,756800.0,4.0,2000.0,CO2e,g,1.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
12404,13450,162311,06528-029-000,812025.0,5.0,2000.0,CO2e,g,1.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
12405,13451,162311,06528-029-000,1411800.0,6.0,2000.0,CO2e,g,1.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
12406,13452,162311,06528-029-000,1520700.0,7.0,2000.0,CO2e,g,1.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
12407,13453,162311,06528-029-000,1235450.0,8.0,2000.0,CO2e,g,1.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
12408,13454,162311,06528-029-000,1132450.0,9.0,2000.0,CO2e,g,1.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
12409,13455,162311,06528-029-000,571625.0,10.0,2000.0,CO2e,g,1.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
12410,13456,162311,06528-029-000,700500.0,11.0,2000.0,CO2e,g,1.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
12411,13457,162311,06528-029-000,1061675.0,12.0,2000.0,CO2e,g,1.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
12412,13458,162311,06528-029-000,1609675.0,1.0,2001.0,CO2e,g,1.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
12413,13459,162311,06528-029-000,742975.0,2.0,2001.0,CO2e,g,1.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
12414,13460,162311,06528-029-000,511925.0,3.0,2001.0,CO2e,g,1.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
12415,13461,162311,06528-029-000,499225.0,4.0,2001.0,CO2e,g,1.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
12416,13462,162311,06528-029-000,749575.0,5.0,2001.0,CO2e,g,1.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
12417,13463,162311,06528-029-000,1091600.0,6.0,2001.0,CO2e,g,1.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
12418,13464,162311,06528-029-000,1584150.0,7.0,2001.0,CO2e,g,1.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
12419,13465,162311,06528-029-000,1212325.0,8.0,2001.0,CO2e,g,1.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
12420,13466,162311,06528-029-000,750225.0,9.0,2001.0,CO2e,g,1.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
12421,13467,162311,06528-029-000,530100.0,10.0,2001.0,CO2e,g,1.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
12422,13468,162311,06528-029-000,507875.0,11.0,2001.0,CO2e,g,1.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
12423,13469,162311,06528-029-000,471875.0,12.0,2001.0,CO2e,g,1.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
12424,13470,162311,06528-029-000,1010875.0,1.0,2002.0,CO2e,g,1.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
12425,13471,162311,06528-029-000,664375.0,2.0,2002.0,CO2e,g,1.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
12426,13472,162311,06528-029-000,462075.0,3.0,2002.0,CO2e,g,1.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13442,14488,162311,06528-029-000,4.0,7.0,2016.0,water,kGal,725.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
13443,14489,162311,06528-029-000,4.0,8.0,2016.0,water,kGal,725.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
13444,14490,162311,06528-029-000,4.0,9.0,2016.0,water,kGal,725.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
13445,14491,162311,06528-029-000,4.0,10.0,2016.0,water,kGal,725.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
13446,14492,162311,06528-029-000,3.0,11.0,2016.0,water,kGal,725.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
13447,14493,162311,06528-029-000,3.0,12.0,2016.0,water,kGal,725.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
13448,14494,162311,06528-029-000,3.0,1.0,2017.0,water,kGal,725.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
13449,14495,162311,06528-029-000,4.0,2.0,2017.0,water,kGal,725.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
13450,14496,162311,06528-029-000,2.0,3.0,2017.0,water,kGal,725.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
13451,14497,162311,06528-029-000,3.0,4.0,2017.0,water,kGal,725.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
13452,14498,162311,06528-029-000,3.0,5.0,2017.0,water,kGal,725.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
13453,14499,162311,06528-029-000,3.0,6.0,2017.0,water,kGal,725.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
13454,14500,162311,06528-029-000,3.0,7.0,2017.0,water,kGal,725.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
13455,14501,162311,06528-029-000,4.0,8.0,2017.0,water,kGal,725.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
13456,14502,162311,06528-029-000,4.0,9.0,2017.0,water,kGal,725.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
13457,14503,162311,06528-029-000,4.0,10.0,2017.0,water,kGal,725.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
13458,14504,162311,06528-029-000,3.0,11.0,2017.0,water,kGal,725.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
13459,14505,162311,06528-029-000,4.0,12.0,2017.0,water,kGal,725.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
13460,14506,162311,06528-029-000,4.0,1.0,2018.0,water,kGal,725.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
13461,14507,162311,06528-029-000,4.0,2.0,2018.0,water,kGal,725.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
13462,14508,162311,06528-029-000,4.0,3.0,2018.0,water,kGal,725.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
13463,14509,162311,06528-029-000,5.0,4.0,2018.0,water,kGal,725.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
13464,14510,162311,06528-029-000,4.0,5.0,2018.0,water,kGal,725.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
13465,14511,162311,06528-029-000,6.0,6.0,2018.0,water,kGal,725.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
13466,14512,162311,06528-029-000,6.0,7.0,2018.0,water,kGal,725.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
13467,14513,162311,06528-029-000,9.0,8.0,2018.0,water,kGal,725.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
13468,14514,162311,06528-029-000,4.0,9.0,2018.0,water,kGal,725.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
13469,14515,162311,06528-029-000,5.0,10.0,2018.0,water,kGal,725.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
13470,14516,162311,06528-029-000,2.0,11.0,2018.0,water,kGal,725.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family
13471,14517,162311,06528-029-000,4.0,12.0,2018.0,water,kGal,725.0,NaN,ANGLEWOOD REPLAT,NaN,NaN,1836,32607,1977,3,2.0,1,single family

#### So I'll delete it from each of the Dfs

In [26]:
clean_before_78 = clean_before_78[clean_before_78['home_id'] != '162311']

# df = df[df.line_race != 0]

In [27]:
len(set(list(clean_before_78['home_id'])))

227

In [28]:
clean_post_78 = clean_post_78[clean_post_78['home_id'] != '162311']

In [29]:
len(set(list(clean_post_78['home_id'])))

183

Merging the two dataframes. We have 184 houses in the post-1978 and 228 in the pre-1978 data bases

In [30]:
all_houses = pd.concat([clean_before_78, clean_post_78], sort=True)

In [31]:
all_houses.head()

,Unnamed: 0,amount,apartment,apartment_id,baths,beds,builtin,family,gco2e_coefficient,home_id,month,parcel,squarefeet,stories,subdivision,subdivision_id,unit,usage_type,year,zip
0,1.0,1450.0,NaN,NaN,2.0,3,1977,single family,1.0,158340,10.0,11515-000-000,804,1,NaN,NaN,g,CO2e,1999.0,32601
1,2.0,1450.0,NaN,NaN,2.0,3,1977,single family,1.0,158340,11.0,11515-000-000,804,1,NaN,NaN,g,CO2e,1999.0,32601
2,3.0,325200.0,NaN,NaN,2.0,3,1977,single family,1.0,158340,12.0,11515-000-000,804,1,NaN,NaN,g,CO2e,1999.0,32601
3,4.0,288200.0,NaN,NaN,2.0,3,1977,single family,1.0,158340,1.0,11515-000-000,804,1,NaN,NaN,g,CO2e,2000.0,32601
4,5.0,278225.0,NaN,NaN,2.0,3,1977,single family,1.0,158340,2.0,11515-000-000,804,1,NaN,NaN,g,CO2e,2000.0,32601

#### The new dataframe has the correct number of houses as it's the sum of the number of houses in each list

In [32]:
len(set(list(all_houses['home_id'])))

410

#### Removing the excess indexing column

In [33]:
all_houses = all_houses.drop(['Unnamed: 0'], axis=1)

In [34]:
all_houses.to_pickle("./all_houses.pkl")

## Loading the electricity and natural gas prices to add to dfs

In [35]:
electricty = pd.read_excel('avgprice_annual_electricity.xlsx')

In [36]:
natural_gas = pd.read_excel('natural_gas_price.xls')

Reducing the electricty data to just include that from Florida

In [37]:
electricity = electricty[electricty['State'] == 'FL']

## Note that the unit for the electricity measurements is cents/killowatthour

In [38]:
electricity.head()

,Year,State,Industry Sector Category,Residential,Commercial,Industrial,Transportation,Other,Total
9,2017,FL,Total Electric Industry,11.61,9.35,7.83,8.62,NaN,10.42
61,2017,FL,Full-Service Providers,11.61,9.35,7.83,8.62,NaN,10.42
176,2016,FL,Total Electric Industry,10.98,8.90,7.69,8.32,NaN,9.91
228,2016,FL,Full-Service Providers,10.98,8.90,7.69,8.32,NaN,9.91
343,2015,FL,Total Electric Industry,11.58,9.50,8.22,8.92,NaN,10.49

#### Deleting all the electricity stuff I don't need

In [39]:
electricity = electricity[electricity['Industry Sector Category'] == 'Total Electric Industry']
electricity.head()

cleaned_electricity = electricity.drop(['State', 'Industry Sector Category', 'Industrial', 'Commercial', 'Transportation', 'Other', 'Total'], axis=1)

### Idea: merge the dataframes on year. First, change the year column so it's the same in both, then merge

In [40]:
cleaned_electricity = cleaned_electricity.rename(columns={'Year': 'year'})

In [41]:
all_houses = pd.merge(all_houses, cleaned_electricity, on='year', how='outer')

In [42]:
all_houses = all_houses.rename(columns={'Residential': 'avg electricity price cents/kwh'})

In [43]:
all_houses

,amount,apartment,apartment_id,baths,beds,builtin,family,gco2e_coefficient,home_id,month,parcel,squarefeet,stories,subdivision,subdivision_id,unit,usage_type,year,zip,avg electricity price cents/kwh
0,1450.0,NaN,NaN,2.0,3,1977,single family,1.0,158340,10.0,11515-000-000,804,1,NaN,NaN,g,CO2e,1999.0,32601,7.73
1,1450.0,NaN,NaN,2.0,3,1977,single family,1.0,158340,11.0,11515-000-000,804,1,NaN,NaN,g,CO2e,1999.0,32601,7.73
2,325200.0,NaN,NaN,2.0,3,1977,single family,1.0,158340,12.0,11515-000-000,804,1,NaN,NaN,g,CO2e,1999.0,32601,7.73
3,350.0,NaN,NaN,2.0,3,1977,single family,925.0,158340,12.0,11515-000-000,804,1,NaN,NaN,kWh,electricity,1999.0,32601,7.73
4,350.0,NaN,NaN,2.0,3,1977,single family,NaN,158340,12.0,11515-000-000,804,1,NaN,NaN,kWh,kWh e,1999.0,32601,7.73
5,2.0,NaN,NaN,2.0,3,1977,single family,725.0,158340,10.0,11515-000-000,804,1,NaN,NaN,kGal,water,1999.0,32601,7.73
6,2.0,NaN,NaN,2.0,3,1977,single family,725.0,158340,11.0,11515-000-000,804,1,NaN,NaN,kGal,water,1999.0,32601,7.73
7,2.0,NaN,NaN,2.0,3,1977,single family,725.0,158340,12.0,11515-000-000,804,1,NaN,NaN,kGal,water,1999.0,32601,7.73
8,848600.0,NaN,NaN,2.0,3,1977,single family,1.0,161279,11.0,06462-035-000,2103,1,BLACK ACRES UNIT 2,NaN,g,CO2e,1999.0,32607,7.73
9,1091650.0,NaN,NaN,2.0,3,1977,single family,1.0,161279,12.0,06462-035-000,2103,1,BLACK ACRES UNIT 2,NaN,g,CO2e,1999.0,32607,7.73
10,858.0,NaN,NaN,2.0,3,1977,single family,925.0,161279,11.0,06462-035-000,2103,1,BLACK ACRES UNIT 2,NaN,kWh,electricity,1999.0,32607,7.73
11,890.0,NaN,NaN,2.0,3,1977,single family,925.0,161279,12.0,06462-035-000,2103,1,BLACK ACRES UNIT 2,NaN,kWh,electricity,1999.0,32607,7.73
12,1121.7,NaN,NaN,2.0,3,1977,single family,NaN,161279,11.0,06462-035-000,2103,1,BLACK ACRES UNIT 2,NaN,kWh,kWh e,1999.0,32607,7.73
13,2325.7,NaN,NaN,2.0,3,1977,single family,NaN,161279,12.0,06462-035-000,2103,1,BLACK ACRES UNIT 2,NaN,kWh,kWh e,1999.0,32607,7.73
14,9.0,NaN,NaN,2.0,3,1977,single family,5300.0,161279,11.0,06462-035-000,2103,1,BLACK ACRES UNIT 2,NaN,therm,natural gas,1999.0,32607,7.73
15,49.0,NaN,NaN,2.0,3,1977,single family,5300.0,161279,12.0,06462-035-000,2103,1,BLACK ACRES UNIT 2,NaN,therm,natural gas,1999.0,32607,7.73
16,10.0,NaN,NaN,2.0,3,1977,single family,725.0,161279,11.0,06462-035-000,2103,1,BLACK ACRES UNIT 2,NaN,kGal,water,1999.0,32607,7.73
17,12.0,NaN,NaN,2.0,3,1977,single family,725.0,161279,12.0,06462-035-000,2103,1,BLACK ACRES UNIT 2,NaN,kGal,water,1999.0,32607,7.73
18,62900.0,NaN,NaN,1.0,2,1978,single family,1.0,158863,10.0,11737-000-000,1112,1,LAKEWAY GROVE-IN NEW GV,NaN,g,CO2e,1999.0,32641,7.73
19,75850.0,NaN,NaN,1.0,2,1978,single family,1.0,158863,11.0,11737-000-000,1112,1,LAKEWAY GROVE-IN NEW GV,NaN,g,CO2e,1999.0,32641,7.73
20,106375.0,NaN,NaN,1.0,2,1978,single family,1.0,158863,12.0,11737-000-000,1112,1,LAKEWAY GROVE-IN NEW GV,NaN,g,CO2e,1999.0,32641,7.73
21,68.0,NaN,NaN,1.0,2,1978,single family,925.0,158863,10.0,11737-000-000,1112,1,LAKEWAY GROVE-IN NEW GV,NaN,kWh,electricity,1999.0,32641,7.73
22,82.0,NaN,NaN,1.0,2,1978,single family,925.0,158863,11.0,11737-000-000,1112,1,LAKEWAY GROVE-IN NEW GV,NaN,kWh,electricity,1999.0,32641,7.73
23,115.0,NaN,NaN,1.0,2,1978,single family,925.0,158863,12.0,11737-000-000,1112,1,LAKEWAY GROVE-IN NEW GV,NaN,kWh,electricity,1999.0,32641,7.73
24,68.0,NaN,NaN,1.0,2,1978,single family,NaN,158863,10.0,11737-000-000,1112,1,LAKEWAY GROVE-IN NEW GV,NaN,kWh,kWh e,1999.0,32641,7.73
25,82.0,NaN,NaN,1.0,2,1978,single family,NaN,158863,11.0,11737-000-000,1112,1,LAKEWAY GROVE-IN NEW GV,NaN,kWh,kWh e,1999.0,32641,7.73
26,115.0,NaN,NaN,1.0,2,1978,single family,NaN,158863,12.0,11737-000-000,1112,1,LAKEWAY GROVE-IN NEW GV,NaN,kWh,kWh e,1999.0,32641,7.73
27,740375.0,NaN,NaN,2.5,4,1977,single family,1.0,155656,11.0,06656-045-027,3389,1,BUCKINGHAM SOUTH UNIT 1,NaN,g,CO2e,1999.0,32607,7.73
28,717825.0,NaN,NaN,2.5,4,1977,single family,1.0,155656,12.0,06656-045-027,3389,1,BUCKINGHAM SOUTH UNIT 1,NaN,g,CO2e,1999.0,32607,7.73
29,722.0,NaN,NaN,2.5,4,1977,single family,925.0,155656,11.0,06656-045-027,3389,1,BUCKINGHAM SOUTH UNIT 1,NaN,kWh,electricity,1999.0,32607,7.73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
355505,95400.0,NaN,NaN,1.0,3,1979,single family,1.0,162624,7.0,14521-000-000,1212,1,BRUSH ADDN TO GVILLE BLK 27,314.0,g,CO2e,1993.0,32601,7.99
355506,106000.0,NaN,NaN,1.0,3,1979,single family,1.0,162624,8.0,14521-000-000,1212,1,BRUSH ADDN TO GVILLE BLK 27,314.0,g,CO2e,1993.0,32601,7.99
355507,100700.0,NaN,NaN,1.0,3,1979,single family,1.0,162624,9.0,14521-000-000,1212,1,BRUSH ADDN TO GVILLE BLK 27,314.0,g,CO2e,1993.0,32601,7.99
355508,100700.0,NaN,NaN,1.0,3,1979,single family,1.0,162624,10.0,14521-000-000,1212,1,BRUSH ADDN TO GVILLE BLK 27,314.0,g,CO2e,1993.0,32601,7.99
355509,185500.0,NaN,NaN,1.0,3,1979,single family,1.0,162624,11.0,14521-000-000,1212,1,BRUSH ADDN TO GVILLE BLK 27,314.0,g,CO2e,1993.0,32601,7.99
355510,259700.0,NaN,NaN,1.0,3,1979,single family,1.0,162624,12.0,14521-000-000,1212,1,BRUSH ADDN TO GVILLE BLK 27,314.0,g,CO2e,1993.0,32601,7.99
355511,2490.5,NaN,NaN,1.0,3,1979,single family,NaN,162624,1.0,14521-000-000,1212,1,BRUSH ADDN TO GVILLE BLK 27,314.0,kWh,kWh e,1993.0,32601,7.99
355512,2256.1,NaN,NaN,1.0,3,1979,single family,NaN,162624,2.0,14521-000-000,1212,1,BRUSH ADDN TO GVILLE BLK 27,314.0,kWh,kWh e,1993.0,32601,7.99
355513,2637.0,NaN,NaN,1.0,3,1979,single family,NaN,162624,3.0,14521-000-000,1212,1,BRUSH ADDN TO GVILLE BLK 27,314.0,kWh,kWh e,1993.0,32601,7.99
355514,2197.5,NaN,NaN,1.0,3,1979,single family,NaN,162624,4.0,14521-000-000,1212,1,BRUSH ADDN TO GVILLE BLK 27,314.0,kWh,kWh e,1993.0,32601,7.99
355515,1113.4,NaN,NaN,1.0,3,1979,single family,NaN,162624,5.0,14521-000-000,1212,1,BRUSH ADDN TO GVILLE BLK 27,314.0,kWh,kWh e,1993.0,32601,7.99
355516,527.4,NaN,NaN,1.0,3,1979,single family,NaN,162624,6.0,14521-000-000,1212,1,BRUSH ADDN TO GVILLE BLK 27,314.0,kWh,kWh e,1993.0,32601,7.99
355517,527.4,NaN,NaN,1.0,3,1979,single family,NaN,162624,7.0,14521-000-000,1212,1,BRUSH ADDN TO GVILLE BLK 27,314.0,kWh,kWh e,1993.0,32601,7.99
355518,586.0,NaN,NaN,1.0,3,1979,single family,NaN,162624,8.0,14521-000-000,1212,1,BRUSH ADDN TO GVILLE BLK 27,314.0,kWh,kWh e,1993.0,32601,7.99
355519,556.7,NaN,NaN,1.0,3,1979,single family,NaN,162624,9.0,14521-000-000,1212,1,BRUSH ADDN TO GVILLE BLK 27,314.0,kWh,kWh e,1993.0,32601,7.99
355520,556.7,NaN,NaN,1.0,3,1979,single family,NaN,162624,10.0,14521-000-000,1212,1,BRUSH ADDN TO GVILLE BLK 27,314.0,kWh,kWh e,1993.0,32601,7.99
355521,1025.5,NaN,NaN,1.0,3,1979,single family,NaN,162624,11.0,14521-000-000,1212,1,BRUSH ADDN TO GVILLE BLK 27,314.0,kWh,kWh e,1993.0,32601,7.99
355522,1435.7,NaN,NaN,1.0,3,1979,single family,NaN,162624,12.0,14521-000-000,1212,1,BRUSH ADDN TO GVILLE BLK 27,314.0,kWh,kWh e,1993.0,32601,7.99
355523,85.0,NaN,NaN,1.0,3,1979,single family,5300.0,162624,1.0,14521-000-000,1212,1,BRUSH ADDN TO GVILLE BLK 27,314.0,therm,natural gas,1993.0,32601,7.99
355524,77.0,NaN,NaN,1.0,3,1979,single family,5300.0,162624,2.0,14521-000-000,1212,1,BRUSH ADDN TO GVILLE BLK 27,314.0,therm,natural gas,1993.0,32601,7.99
355525,90.0,NaN,NaN,1.0,3,1979,single family,5300.0,162624,3.0,14521-000-000,1212,1,BRUSH ADDN TO GVILLE BLK 27,314.0,therm,natural gas,1993.0,32601,7.99
355526,75.0,NaN,NaN,1.0,3,1979,single family,5300.0,162624,4.0,14521-000-000,1212,1,BRUSH ADDN TO GVILLE BLK 27,314.0,therm,natural gas,1993.0,32601,7.99
355527,38.0,NaN,NaN,1.0,3,1979,single family,5300.0,162624,5.0,14521-000-000,1212,1,BRUSH ADDN TO GVILLE BLK 27,314.0,therm,natural gas,1993.0,32601,7.99
355528,18.0,NaN,NaN,1.0,3,1979,single family,5300.0,162624,6.0,14521-000-000,1212,1,BRUSH ADDN TO GVILLE BLK 27,314.0,therm,natural gas,1993.0,32601,7.99
355529,18.0,NaN,NaN,1.0,3,1979,single family,5300.0,162624,7.0,14521-000-000,1212,1,BRUSH ADDN TO GVILLE BLK 27,314.0,therm,natural gas,1993.0,32601,7.99
355530,20.0,NaN,NaN,1.0,3,1979,single family,5300.0,162624,8.0,14521-000-000,1212,1,BRUSH ADDN TO GVILLE BLK 27,314.0,therm,natural gas,1993.0,32601,7.99
355531,19.0,NaN,NaN,1.0,3,1979,single family,5300.0,162624,9.0,14521-000-000,1212,1,BRUSH ADDN TO GVILLE BLK 27,314.0,therm,natural gas,1993.0,32601,7.99
355532,19.0,NaN,NaN,1.0,3,1979,single family,5300.0,162624,10.0,14521-000-000,1212,1,BRUSH ADDN TO GVILLE BLK 27,314.0,therm,natural gas,1993.0,32601,7.99
355533,35.0,NaN,NaN,1.0,3,1979,single family,5300.0,162624,11.0,14521-000-000,1212,1,BRUSH ADDN TO GVILLE BLK 27,314.0,therm,natural gas,1993.0,32601,7.99
355534,49.0,NaN,NaN,1.0,3,1979,single family,5300.0,162624,12.0,14521-000-000,1212,1,BRUSH ADDN TO GVILLE BLK 27,314.0,therm,natural gas,1993.0,32601,7.99

#### Same process now for natural gas

In [44]:
natural_gas.head()

,Date,Florida Price of Natural Gas Delivered to Residential Consumers (Dollars per Thousand Cubic Feet)
0,1989-01-15,7.26
1,1989-02-15,7.55
2,1989-03-15,7.12
3,1989-04-15,7.92
4,1989-05-15,8.91

In [45]:
natural_gas = natural_gas.rename(columns={'Florida Price of Natural Gas Delivered to Residential Consumers (Dollars per Thousand Cubic Feet)': 'avg natural gas price $/thousand cubic feet'})

In [46]:
natural_gas['Date'] = natural_gas['Date'].apply(lambda x: x.year)

In [47]:
natural_gas = natural_gas.rename(columns={'Date': 'year'})

In [48]:
all_houses = pd.merge(all_houses, natural_gas, on='year', how='outer')

In [49]:
all_houses.head()

,amount,apartment,apartment_id,baths,beds,builtin,family,gco2e_coefficient,home_id,month,...,squarefeet,stories,subdivision,subdivision_id,unit,usage_type,year,zip,avg electricity price cents/kwh,avg natural gas price $/thousand cubic feet
0,1450.0,NaN,NaN,2.0,3.0,1977.0,single family,1.0,158340,10.0,...,804.0,1.0,NaN,NaN,g,CO2e,1999.0,32601.0,7.73,9.75
1,1450.0,NaN,NaN,2.0,3.0,1977.0,single family,1.0,158340,10.0,...,804.0,1.0,NaN,NaN,g,CO2e,1999.0,32601.0,7.73,10.71
2,1450.0,NaN,NaN,2.0,3.0,1977.0,single family,1.0,158340,10.0,...,804.0,1.0,NaN,NaN,g,CO2e,1999.0,32601.0,7.73,10.15
3,1450.0,NaN,NaN,2.0,3.0,1977.0,single family,1.0,158340,10.0,...,804.0,1.0,NaN,NaN,g,CO2e,1999.0,32601.0,7.73,11.14
4,1450.0,NaN,NaN,2.0,3.0,1977.0,single family,1.0,158340,10.0,...,804.0,1.0,NaN,NaN,g,CO2e,1999.0,32601.0,7.73,12.46

### Adding a proxy for revenue

In [50]:
all_houses.head()

,amount,apartment,apartment_id,baths,beds,builtin,family,gco2e_coefficient,home_id,month,...,squarefeet,stories,subdivision,subdivision_id,unit,usage_type,year,zip,avg electricity price cents/kwh,avg natural gas price $/thousand cubic feet
0,1450.0,NaN,NaN,2.0,3.0,1977.0,single family,1.0,158340,10.0,...,804.0,1.0,NaN,NaN,g,CO2e,1999.0,32601.0,7.73,9.75
1,1450.0,NaN,NaN,2.0,3.0,1977.0,single family,1.0,158340,10.0,...,804.0,1.0,NaN,NaN,g,CO2e,1999.0,32601.0,7.73,10.71
2,1450.0,NaN,NaN,2.0,3.0,1977.0,single family,1.0,158340,10.0,...,804.0,1.0,NaN,NaN,g,CO2e,1999.0,32601.0,7.73,10.15
3,1450.0,NaN,NaN,2.0,3.0,1977.0,single family,1.0,158340,10.0,...,804.0,1.0,NaN,NaN,g,CO2e,1999.0,32601.0,7.73,11.14
4,1450.0,NaN,NaN,2.0,3.0,1977.0,single family,1.0,158340,10.0,...,804.0,1.0,NaN,NaN,g,CO2e,1999.0,32601.0,7.73,12.46

### Deleting unecessary columns

In [51]:
all_houses = all_houses.drop(['parcel', 'subdivision', 'subdivision_id', 'apartment_id', 'unit'], 1)

### Creating a correlation matrix

In [52]:
all_houses.corr()

,amount,baths,beds,builtin,gco2e_coefficient,month,squarefeet,stories,year,zip,avg electricity price cents/kwh,avg natural gas price $/thousand cubic feet
amount,1.000000,0.084702,0.077065,0.000847,-0.376370,0.002825,0.096691,0.045105,-0.050144,0.005424,-0.040786,-0.019327
baths,0.084702,1.000000,0.708024,-0.130070,0.036399,-0.001930,0.631693,0.291800,-0.055526,0.123296,-0.064736,-0.029302
beds,0.077065,0.708024,1.000000,-0.164474,0.078015,-0.003660,0.607237,0.124774,-0.095537,0.060267,-0.101997,-0.049119
builtin,0.000847,-0.130070,-0.164474,1.000000,-0.076944,0.001467,-0.049919,0.063037,0.024066,-0.026524,0.029174,0.012668
gco2e_coefficient,-0.376370,0.036399,0.078015,-0.076944,1.000000,0.006047,0.032855,-0.050031,-0.045557,0.008943,-0.025071,-0.025284
month,0.002825,-0.001930,-0.003660,0.001467,0.006047,1.000000,-0.000597,0.001543,-0.008661,0.000589,-0.017285,-0.016963
squarefeet,0.096691,0.631693,0.607237,-0.049919,0.032855,-0.000597,1.000000,0.270225,-0.040806,0.058182,-0.048181,-0.023169
stories,0.045105,0.291800,0.124774,0.063037,-0.050031,0.001543,0.270225,1.000000,0.017869,-0.023154,0.020391,0.009094
year,-0.050144,-0.055526,-0.095537,0.024066,-0.045557,-0.008661,-0.040806,0.017869,1.000000,0.001567,0.813278,0.502022
zip,0.005424,0.123296,0.060267,-0.026524,0.008943,0.000589,0.058182,-0.023154,0.001567,1.000000,0.003850,0.004217
avg electricity price cents/kwh,-0.040786,-0.064736,-0.101997,0.029174,-0.025071,-0.017285,-0.048181,0.020391,0.813278,0.003850,1.000000,0.555402
avg natural gas price $/thousand cubic feet,-0.019327,-0.029302,-0.049119,0.012668,-0.025284,-0.016963,-0.023169,0.009094,0.502022,0.004217,0.555402,1.000000